### ISSUE TITLE
外接显示屏不饿能用吗

### ISSUE THREAD

**Issue by yuduobing** [XingKong746/RedmiBook16-Hackintosh#1]

**Comment by XingKong746** [comment]
内置HDMI不行可以通过Type-C扩展坞(不一定都行)输出，但我并没有弄Type HDMI，一没设备，二没时间🌚

**Comment by hariksone** [comment]
Type-C dock station doesn't work. no hdmi and even usb output

**Comment by XingKong746** [comment]
> Type-C dock station doesn't work. no hdmi and even usb output
Type-C docking station to HDMI does not work properly in Hackintosh, but Type-C to USB is no problem.

**Comment by XingKong746** [comment]
> Type-C dock station doesn't work. no hdmi and even usb output


Type-C docking station to HDMI does not work properly in the black apple, but Type-C to USB is no problem.

**Comment by XingKong746** [comment]
> Type-C dock station doesn't work. no hdmi and even usb output


If you need an external monitor, the available solution is "displaylink docking station", but it is limited to monitors with 2K and lower resolutions
